@set ALLUSERSPROFILE=C:\ProgramData
@set ANDROID_SDK_ROOT=C:\Dev\android-sdk-windows
@set ANT_ROOT=C:\Dev\apache-ant-1.9.7\bin
@set APPDATA=C:\Users\rusbaron\AppData\Roaming
@set CLIENTNAME=WS0930
@set COCOS_CONSOLE_ROOT=C:\Dev\cocos2d-x-3.13.1\tools\cocos2d-console\bin
@set COCOS_TEMPLATES_ROOT=C:\Dev\cocos2d-x-3.13.1\templates
@set COCOS_X_ROOT=C:\Dev
@set CommonProgramFiles=C:\Program Files\Common Files
@set CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
@set CommonProgramW6432=C:\Program Files\Common Files
@set COMPUTERNAME=SVAROG
@set ComSpec=C:\Windows\system32\cmd.exe
@set DevEnvDir=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\
@set FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
@set FPS_BROWSER_USER_PROFILE_STRING=Default
@set Framework40Version=v4.0
@set FrameworkDir=C:\Windows\Microsoft.NET\Framework\
@set FrameworkDIR32=C:\Windows\Microsoft.NET\Framework\
@set FrameworkVersion=v4.0.30319
@set FrameworkVersion32=v4.0.30319
@set FugueRepository=C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\TEAM TOOLS\STATIC ANALYSIS TOOLS\FxCop\Repository
@set GTK_BASEPATH=C:\Program Files (x86)\GtkSharp\2.12\
@set HOMEDRIVE=C:
@set HOMEPATH=\Users\rusbaron
@set INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um;C:\Program Files (x86)\Windows Kits\8.1\include\\shared;C:\Program Files (x86)\Windows Kits\8.1\include\\um;C:\Program Files (x86)\Windows Kits\8.1\include\\winrt;
@set LIB=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x86;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x86;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86;
@set LIBPATH=C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB;C:\Program Files (x86)\Windows Kits\8.1\References\CommonConfiguration\Neutral;\Microsoft.VCLibs\14.0\References\CommonConfiguration\neutral;
@set LOCALAPPDATA=C:\Users\rusbaron\AppData\Local
@set LOGONSERVER=\\SVAROG
@set MSBuildLoadMicrosoftTargetsReadOnly=true
@set NDK_ROOT=C:\Dev\android-ndk-r13b
@set NETFXSDKDir=C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\
@set NUMBER_OF_PROCESSORS=4
@set OS=Windows_NT
@set Path=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\MSBuild\14.0\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\8.1\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\NativeBinaries\x86;C:\Python27\;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Dev\cocos2d-x-3.13.1\templates;C:\Dev\cocos2d-x-3.13.1\tools\cocos2d-console\bin;C:\Users\rusbaron\AppData\Local\Programs\Python\Python35\Scripts\;C:\Users\rusbaron\AppData\Local\Programs\Python\Python35\;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
@set PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
@set PkgDefApplicationConfigFile=C:\Users\rusbaron\AppData\Local\Microsoft\VisualStudio\14.0\devenv.exe.config
@set PROCESSOR_ARCHITECTURE=AMD64
@set PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
@set PROCESSOR_LEVEL=6
@set PROCESSOR_REVISION=2a07
@set ProgramData=C:\ProgramData
@set ProgramFiles=C:\Program Files
@set ProgramFiles(x86)=C:\Program Files (x86)
@set ProgramW6432=C:\Program Files
@set PROMPT=$P$G
@set PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
@set PUBLIC=C:\Users\Public
@set SESSIONNAME=RDP-Tcp#1
@set SystemDrive=C:
@set SystemRoot=C:\Windows
@set TEMP=C:\Users\rusbaron\AppData\Local\Temp
@set TMP=C:\Users\rusbaron\AppData\Local\Temp
@set UCRTVersion=10.0.10240.0
@set UniversalCRTSdkDir=C:\Program Files (x86)\Windows Kits\10\
@set USERDOMAIN=SVAROG
@set USERDOMAIN_ROAMINGPROFILE=SVAROG
@set USERNAME=rusbaron
@set USERPROFILE=C:\Users\rusbaron
@set VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
@set VisualStudioDir=C:\Users\rusbaron\Documents\Visual Studio 2015
@set VisualStudioEdition=Microsoft Visual Studio Professional 2015
@set VisualStudioVersion=14.0
@set VS140COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
@set VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio 14.0\
@set VSLANG=1033
@set VSSDK140Install=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VSSDK\
@set windir=C:\Windows
@set WindowsLibPath=C:\Program Files (x86)\Windows Kits\8.1\References\CommonConfiguration\Neutral
@set WindowsSdkDir=C:\Program Files (x86)\Windows Kits\8.1\
@set WindowsSDKLibVersion=winv6.3\
@set WindowsSDKVersion=\
@set WindowsSDK_ExecutablePath_x64=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\
@set WindowsSDK_ExecutablePath_x86=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\
@set _PTVS_PID=8632

@call "C:\Program Files (x86)\PVS-Studio\x86\clang.exe" @"C:\Users\rusbaron\Projects\InventoryTask\cocos2d\cocos\2d\AssetsManager.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1